language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libxml2-dev libsword-utils libxml2-utils

install:
  - git clone https://github.com/krisek/sword-test
  - pip install -r sword-test/requirements.txt
# command to run tests
script:
  - cd sword-test
  - pytest --modulename HunKar --moduleconf ../hunkar.conf -vvv --modulexml ../hunkaroli_rev.osis.xml -vvv -s
