language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - sudo apt update
  - sudo apt install -y osis2mod libxml2-utils
  - git clone https://github.com/krisek/sword-test
  - pip install -r sword-test/requirements.txt
# command to run tests
script:
  - cd sword-test
  - pytest --modulename HunKar --moduleconf ../hunkar.conf -vvv --modulexml ../hunkaroli_revosis.xml -vvv -s
